# Generated by Django 4.0.6 on 2022-07-07 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Happyface4", "0002_rename_warninglevels_instancestatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instancestatus",
            old_name="warning",
            new_name="status",
        ),
    ]
