# Generated by Django 4.1.1 on 2022-09-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Happyface4", "0003_rename_warning_instancestatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instancestatus",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (-2, "technical issue"),
                    (-1, "info"),
                    (0, "ok"),
                    (1, "warning"),
                    (2, "critical"),
                ],
                verbose_name="status of the instance (-2, 'technical issue'),         (-1, 'info'), (0, 'ok'), (1, 'warning'), (2, 'critical')",
            ),
        ),
    ]
